project:
  type: book
  output-dir: docs

book:
  title: "Dissemination using Quarto and Github Pages"
  author: "James Bartlett"
  date: "03/20/2025"
  repo-url: https://github.com/BartlettJE/dissemination_quarto
  repo-actions: [issue, source]
  downloads:
    - pdf
  chapters:
    - index.qmd
    - workshop_prep.qmd
    - part: "Writing Books"
      chapters:
        - quarto_books.qmd
        - psyteachr_template.qmd
    - part: "Sharing Presentations"
      chapters:
        - quarto_presentations.qmd
    - part: "Creating Websites"
      chapters:
        - quarto_websites.qmd
    - part: "General Quarto Resources"
      chapters:
        - quarto_features.qmd
    - references.qmd

bibliography: include/references.bib

csl: include/apa.csl

format:
  html:
    theme: cosmo
    css:   
      - include/webex.css
      - include/glossary.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt

editor: visual

