project:
  type: book

book:
  title: "PsyTeachR Book Template Workshop"
  author: "James Bartlett"
  date: "07/19/2024"
  chapters:
    - index.qmd
    - workshop_prep.qmd
    - workshop_guide.qmd
    - book_conventions.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

