project:
  type: book
  output-dir: docs

book:
  title: "PsyTeachR Book Template Workshop"
  author: "James Bartlett"
  date: "07/19/2024"
  chapters:
    - index.qmd
    - workshop_prep.qmd
    - workshop_guide.qmd
    - book_conventions.qmd
    - references.qmd

bibliography: include/references.bib

csl: include/apa.csl

format:
  html:
    theme: cosmo
    css:   
      - include/webex.css
      - include/glossary.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt

editor: visual

